---
title: "Financial data analysis"
author: "Arina Agaronyan"
format: 
  html: 
    echo: false 
---

```{r config}
#| message: false
here::i_am("dplyr-102.Rproj")
library(here)
library(vroom) ## or readr
library(dplyr)
library(tidyr)
library(ggplot2)
theme_set(theme_bw())
```

## Data loading

```{r load_data}
#| message: false
clients <- vroom(here("data", "client.csv")) ## split file name into directories, then file name
accounts <- vroom(here("data", "account.csv"))
disp <- vroom(here("data", "disp.csv"))
```


## Joining data tables
A collection of joining functions of the form '*_join'.

### Inner join

```{r da}
da <- inner_join(accounts, disp) ## merges data using the one same variable (account_id here)
```

```{r cda}
cda <- inner_join(clients, da, by = join_by(client_id), suffix = c("_home", "_bank")) 
#join - look for common vars and join on those vars, but here leads to removal of some values (~10%) which have mismatching values for a var (due to moving...- don't live where the bank is) so have to add specification of joinby
#by = join by makes two vers of other common var - district_id.x/y - can rename
```




